CREATE DATABASE SHOPZZ

CREATE TABLE Shop (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255),
  latitude NUMERIC(18,15) NOT NULL,
  longitude NUMERIC(18,15) NOT NULL,
  image VARCHAR(255)
) Engine=InnoDB;